sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then
      phpenv config-rm xdebug.ini || echo "No xdebug config.";
    fi
  - travis_retry wget https://github.com/summerwind/h2spec/releases/latest/download/h2spec_linux_amd64.tar.gz
  - tar -xzf h2spec_linux_amd64.tar.gz
  - php test/test-server.php &
  - SERVER_PID = $!

install:
  - travis_retry composer update -n --prefer-dist
  - travis_retry wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.2/coveralls.phar
  - chmod +x coveralls.phar

script:
  - php -dzend.assertions=1 -dassert.exception=1 vendor/bin/phpunit --coverage-text --verbose --coverage-clover build/logs/clover.xml
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - travis_retry ./coveralls.phar -v
  - kill $SERVER_PID

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
